[package]
name = "rutile_r2r"
version = "0.3.2"
edition = "2024"
authors = ["David Doose <david.doose@onera.fr>"]
license = "LGPL-3.0-only"
description = "Simple ROS2 r2r binding"
repository = "https://github.com/DavidD12/rutile_r2r"
keywords = ["RSO2", "r2r"]

[env]
IDL_PACKAGE_FILTER = "std_msgs,example_interfaces"

[dependencies]
futures = { version = "0.3.31", features = ["thread-pool"] }
r2r = "0.9.4"
rand = "0.9.0"

[lib]
name = "rutile"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "bin/main.rs"

[[bin]]
name = "wall_timer"
path = "bin/wall_timer.rs"

[[bin]]
name = "publisher"
path = "bin/publisher.rs"

[[bin]]
name = "subscriber"
path = "bin/subscriber.rs"

[[bin]]
name = "service"
path = "bin/service.rs"

[[bin]]
name = "client"
path = "bin/client.rs"

# [[bin]]
# name = "client_sync"
# path = "bin/client_sync.rs"

# [[bin]]
# name = "core_node"
# path = "bin/core_node.rs"

[[bin]]
name = "future_client_unlock"
path = "bin/future_client_unlock.rs"

[[bin]]
name = "future_publisher"
path = "bin/future_publisher.rs"

[[bin]]
name = "future_subscriber"
path = "bin/future_subscriber.rs"

[[bin]]
name = "future_service"
path = "bin/future_service.rs"

[[bin]]
name = "future_client"
path = "bin/future_client.rs"
